# Generated by Django 4.2 on 2025-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор ссылки')),
                ('target_url', models.URLField(verbose_name='Ссылка для редиректа')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Количество переходов')),
            ],
            options={
                'verbose_name': 'Отслеживаемая ссылка',
                'verbose_name_plural': 'Отслеживаемые ссылки',
            },
        ),
    ]
