# Generated by Django 4.2 on 2025-07-23 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Имя бокса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('length', models.PositiveSmallIntegerField(verbose_name='Длина')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Высота')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('is_busy', models.BooleanField(default=False, verbose_name='Занят ли бокс')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('address', models.CharField(max_length=60, verbose_name='Адрес')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
                ('contacts', models.CharField(blank=True, max_length=150, verbose_name='Контакты')),
                ('temperature', models.IntegerField(blank=True, null=True, verbose_name='Температура на складе')),
                ('ceiling_height', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Высота потолка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата начала аренды')),
                ('date_end', models.DateField(verbose_name='Дата конца аренды')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse_app.box', verbose_name='Бокс')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='warehouse_app.warehouse', verbose_name='Склад'),
        ),
    ]
