# Generated by Django 4.2 on 2025-07-22 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Высота потолка'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='contacts',
            field=models.CharField(blank=True, max_length=150, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото склада'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Температура на складе'),
        ),
        migrations.AlterField(
            model_name='box',
            name='is_busy',
            field=models.BooleanField(default=False, verbose_name='Занят ли бокс'),
        ),
        migrations.AlterField(
            model_name='box',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='warehouse_app.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='order',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse_app.box', verbose_name='Бокс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала аренды'),
        ),
    ]
