# Generated by Django 4.2 on 2025-07-23 20:11

from django.db import migrations, models
import django.db.models.deletion
import warehouse_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=warehouse_app.models.get_directory_path, verbose_name='Фото склада'),
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuffs', to='warehouse_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
            },
        ),
    ]
