# Generated by Django 4.2 on 2025-07-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0002_warehouse_ceiling_height_warehouse_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='name',
            field=models.CharField(default=1, max_length=10, verbose_name='Имя бокса'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuffs', to='warehouse_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
            },
        ),
    ]
