# Generated by Django 4.2 on 2025-07-23 11:43

from django.db import migrations, models
import warehouse_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0003_box_name_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=warehouse_app.models.get_directory_path, verbose_name='Фото склада'),
        ),
    ]
