# Generated by Django 4.2 on 2025-07-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0006_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes', verbose_name='QR-код'),
        ),
    ]
