# Generated by Django 4.2 on 2025-07-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0007_order_qr_code'),
        ('warehouse_app', '0007_profile'),
    ]

    operations = [
    ]
