# Generated by Django 4.2 on 2025-07-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0008_merge_0007_order_qr_code_0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=70, verbose_name='Адрес приёма вещей'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(blank=True, verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Высота'),
        ),
    ]
