# Generated by Django 4.2 on 2025-07-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0009_order_address_order_items_alter_box_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Номер телефона'),
        ),
    ]
