# Generated by Django 4.2 on 2025-07-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0010_order_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promo',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
    ]
