# Generated by Django 4.2 on 2025-07-27 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_promo'),
        ('warehouse_app', '0012_callbackrequest_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promo.promo', verbose_name='Промокод'),
        ),
    ]
