# Generated by Django 4.2 on 2025-07-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0013_order_promocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stuff',
        ),
    ]
