# Generated by Django 4.2 on 2025-07-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0014_delete_stuff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='ceiling_height',
        ),
    ]
